%%  coding: latin-1
%%------------------------------------------------------------
%%
%% Implementation stub file
%% 
%% Target: CosNotifyFilter_InvalidGrammar
%% Source: /net/isildur/ldisk/daily_build/20_prebuild_opu_o.2018-03-13_21/otp_src_20/lib/cosNotification/src/CosNotifyFilter.idl
%% IC vsn: 4.4.3
%% 
%% This file is automatically generated. DO NOT EDIT IT.
%%
%%------------------------------------------------------------

-module('CosNotifyFilter_InvalidGrammar').
-ic_compiled("4_4_3").


-include("CosNotifyFilter.hrl").

-export([tc/0,id/0,name/0]).



%% returns type code
tc() -> {tk_except,"IDL:omg.org/CosNotifyFilter/InvalidGrammar:1.0",
                   "InvalidGrammar",[]}.

%% returns id
id() -> "IDL:omg.org/CosNotifyFilter/InvalidGrammar:1.0".

%% returns name
name() -> "CosNotifyFilter_InvalidGrammar".



