%%  coding: latin-1
%%------------------------------------------------------------
%%
%% Implementation stub file
%% 
%% Target: CosNotifyChannelAdmin_ConnectionAlreadyActive
%% Source: /net/isildur/ldisk/daily_build/20_prebuild_opu_o.2018-03-13_21/otp_src_20/lib/cosNotification/src/CosNotifyChannelAdmin.idl
%% IC vsn: 4.4.3
%% 
%% This file is automatically generated. DO NOT EDIT IT.
%%
%%------------------------------------------------------------

-module('CosNotifyChannelAdmin_ConnectionAlreadyActive').
-ic_compiled("4_4_3").


-include("CosNotifyChannelAdmin.hrl").

-export([tc/0,id/0,name/0]).



%% returns type code
tc() -> {tk_except,"IDL:omg.org/CosNotifyChannelAdmin/ConnectionAlreadyActive:1.0",
                   "ConnectionAlreadyActive",[]}.

%% returns id
id() -> "IDL:omg.org/CosNotifyChannelAdmin/ConnectionAlreadyActive:1.0".

%% returns name
name() -> "CosNotifyChannelAdmin_ConnectionAlreadyActive".



