%%  coding: latin-1
%%------------------------------------------------------------
%%
%% Implementation stub file
%% 
%% Target: CosPropertyService_FixedProperty
%% Source: /net/isildur/ldisk/daily_build/20_prebuild_opu_o.2018-03-13_21/otp_src_20/lib/cosProperty/src/CosProperty.idl
%% IC vsn: 4.4.3
%% 
%% This file is automatically generated. DO NOT EDIT IT.
%%
%%------------------------------------------------------------

-module('CosPropertyService_FixedProperty').
-ic_compiled("4_4_3").


-include("CosPropertyService.hrl").

-export([tc/0,id/0,name/0]).



%% returns type code
tc() -> {tk_except,"IDL:omg.org/CosPropertyService/FixedProperty:1.0",
                   "FixedProperty",[]}.

%% returns id
id() -> "IDL:omg.org/CosPropertyService/FixedProperty:1.0".

%% returns name
name() -> "CosPropertyService_FixedProperty".



