%%  coding: latin-1
%%------------------------------------------------------------
%%
%% Implementation stub file
%% 
%% Target: CosEventChannelAdmin_TypeError
%% Source: /net/isildur/ldisk/daily_build/20_prebuild_opu_o.2018-03-13_21/otp_src_20/lib/cosEvent/src/CosEventChannelAdmin.idl
%% IC vsn: 4.4.3
%% 
%% This file is automatically generated. DO NOT EDIT IT.
%%
%%------------------------------------------------------------

-module('CosEventChannelAdmin_TypeError').
-ic_compiled("4_4_3").


-include("CosEventChannelAdmin.hrl").

-export([tc/0,id/0,name/0]).



%% returns type code
tc() -> {tk_except,"IDL:omg.org/CosEventChannelAdmin/TypeError:1.0",
                   "TypeError",[]}.

%% returns id
id() -> "IDL:omg.org/CosEventChannelAdmin/TypeError:1.0".

%% returns name
name() -> "CosEventChannelAdmin_TypeError".



