%%  coding: latin-1
%%------------------------------------------------------------
%%
%% Implementation stub file
%% 
%% Target: CosTransactions_HeuristicRollback
%% Source: /net/isildur/ldisk/daily_build/20_prebuild_opu_o.2018-03-13_21/otp_src_20/lib/cosTransactions/src/CosTransactions.idl
%% IC vsn: 4.4.3
%% 
%% This file is automatically generated. DO NOT EDIT IT.
%%
%%------------------------------------------------------------

-module('CosTransactions_HeuristicRollback').
-ic_compiled("4_4_3").


-include("CosTransactions.hrl").

-export([tc/0,id/0,name/0]).



%% returns type code
tc() -> {tk_except,"IDL:omg.org/CosTransactions/HeuristicRollback:1.0",
                   "HeuristicRollback",[]}.

%% returns id
id() -> "IDL:omg.org/CosTransactions/HeuristicRollback:1.0".

%% returns name
name() -> "CosTransactions_HeuristicRollback".



