%%  coding: latin-1
%%------------------------------------------------------------
%%
%% Erlang header file
%% 
%% Target: CosEventDomainAdmin_EventDomainFactory
%% Source: /net/isildur/ldisk/daily_build/20_prebuild_opu_o.2018-03-13_21/otp_src_20/lib/cosEventDomain/src/CosEventDomainAdmin.idl
%% IC vsn: 4.4.3
%% 
%% This file is automatically generated. DO NOT EDIT IT.
%%
%%------------------------------------------------------------


-ifndef(COSEVENTDOMAINADMIN_EVENTDOMAINFACTORY_HRL).
-define(COSEVENTDOMAINADMIN_EVENTDOMAINFACTORY_HRL, true).




-endif.


